;PROGRAM 4 OF LAB 1
;FILENAME: Lab1d.asm
;FILE FORMAT: EXE
.MODEL MEDIUM
.STACK 100
.DATA
MESSAGE DB ?,?,' IS THE ADDRESS',0DH,0AH,'$'
VAR DB 10h
.CODE
MAIN PROC FAR
.STARTUP
LEA DX,VAR ;LOAD ADDRESS
ADD DX,3030h ;CONVERT TO ASCII
MOV MESSAGE, DH ;STORE ADDRESS
MOV MESSAGE + 1, DL ;STORE ADDRESS
LEA DX,MESSAGE ;PREPARE FOR PRINT
MOV AH,9 ;SPECIFY PRINT STRING FUNCTION
INT 21H ;CALL DOS
.EXIT
MAIN ENDP
END